version: '2'

services:
  reverse-proxy-container:
    image: 447993352427.dkr.ecr.ap-northeast-2.amazonaws.com/reverse-proxy:latest
    build:
      context: ./nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - tuning-app-container
    depends_on:
      - tuning-app-container
  tuning-app-container:
    image: 447993352427.dkr.ecr.ap-northeast-2.amazonaws.com/tuning-app:latest
    build:
      context: ./app
    ports:
      - 3000:3000
    networks:
      - default
